language: scala
sudo: required
dist: xenial

branches:
  only:
  - master
  - develop

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/spark
    - $HOME/.sbt/

jdk:
  - openjdk8

scala:
- 2.12.10

sudo: false

addons:
  apt:
    packages:
        - axel

install:
  # Download spark 2.4.5
  - "[ -f spark ] || mkdir spark && cd spark && axel https://archive.apache.org/dist/spark/spark-2.4.5/spark-2.4.5-bin-without-hadoop-scala-2.12.tgz && cd .."
  - "tar -xf ./spark/spark-2.4.5-bin-without-hadoop-scala-2.12.tgz"
  - "export SPARK_HOME=`pwd`/spark-2.4.5-bin-without-hadoop-scala-2.12"
  - echo "spark.yarn.jars=$SPARK_HOME/jars/*.jar" > $SPARK_HOME/conf/spark-defaults.conf

script:
   - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    recipients:
      - rainer.stuetz@ait.ac.at
    on_success: never
    on_failure: always
