name: sbt test

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java:
          - 8

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Test with SBT
      run: |
        export SBT_OPTS="-Xmx1G -XX:+CMSClassUnloadingEnabled -Xss2M -Duser.timezone=UTC"
        sbt test
